on:
  push:
    branches:
      - dev
      - release
    paths:
      - .github/workflows/**
      - src/**
      - pom.xml

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 8

      - name: Create Release Version
        run: |
          PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          BUILD_TIMESTAMP=$(date --utc +'%Y-%m-%dT%H:%M:%SZ')

          if [ $GITHUB_REF_NAME == "release" ]; then
            RELEASE_VERSION="${PROJECT_VERSION}"
            BUILD_TYPE="release"
          else
            COMMIT_SHA=$(echo $GITHUB_SHA | cut -c 1-7)
            RELEASE_VERSION="${PROJECT_VERSION}-${COMMIT_SHA}-dev"
            BUILD_TYPE="development"
          fi

          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          mvn versions:set -DnewVersion="${RELEASE_VERSION}" -DgenerateBackupPoms=false

          {
            echo "release_version=${RELEASE_VERSION}"
            echo "build_type=${BUILD_TYPE}"
            echo "build_timestamp=${BUILD_TIMESTAMP}"
            echo "git_commit=${GITHUB_SHA}"
          } > src/main/resources/version.properties

      - name: Build JAR
        run: mvn clean package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: ${{ env.RELEASE_VERSION }}
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}